version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.15.5-alpine
    volumes:
      - ./nginx-conf:/etc/nginx/
    ports:
      - "8090:80"
      - "443:443"
  # Meta nodes
  meta-node1:
    image: influxdb:1.6.3-meta
    container_name: meta1
    volumes:
      - ./meta-nodes/meta1:/var/lib/influxdb
      - ./meta-nodes/config/:/etc/influxdb
    env_file:
      - variables.env
    environment:
      - INFLUXDB_HOSTNAME=meta1
    ports:
    # Meta nodes communicate ovet ports 8088, 8089, and 8091
    - "18088:8088"
    - "18089:8089"
    # UDP Port
    - "18091:8091"

  meta-node2:
    image: influxdb:1.6.3-meta
    container_name: meta2
    volumes:
      # Mount meta directory
      - ./meta-nodes/meta2:/var/lib/influxdb
      - ./meta-nodes/config/:/etc/influxdb
    env_file:
      - variables.env
    environment:
      - INFLUXDB_HOSTNAME=meta2
    ports:
    - "28088:8088"
    - "28089:8089"
    - "28091:8091"

  meta-node3:
    container_name: meta3
    image: influxdb:1.6.3-meta
    volumes:
      - ./meta-nodes/meta3:/var/lib/influxdb
      - ./meta-nodes/config/:/etc/influxdb
    env_file:
      - variables.env
    environment:
      - INFLUXDB_HOSTNAME=meta3
    ports:
    - "38088:8088"
    - "38089:8089"
    - "38091:8091"

  # Data nodes
  data-node1:
    image: influxdb:1.6.3-data
    container_name: data1
    volumes:
      # Mount data directory
      - ./data-nodes/data1:/var/lib/influxdb
      - ./data-nodes/config/:/etc/influxdb
    env_file:
      - variables.env
    environment:
      - INFLUXDB_HOSTNAME=data1
    ports:
      - "18086:8086"
      - "18082:8082"

  data-node2:
    image: influxdb:1.6.3-data
    container_name: data2
    volumes:
      - ./data-nodes/data2:/var/lib/influxdb
      - ./data-nodes/config/:/etc/influxdb
    env_file:
      - variables.env
    environment:
      - INFLUXDB_HOSTNAME=data2
    ports:
      - "28086:8086"
      - "28082:8082"
